name: boond_api
description: Boond Manager API.
version: 0.0.1
# homepage: https://www.example.com
author: patrouil

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
#  path: ^1.6.0
  # utilities
  logging: ^0.11.4
  http: ^0.12.1
  http_auth : ^0.2.9

dev_dependencies:
  pedantic: ^1.8.0  # control coding style. see analysis_options.yaml
  test: ^1.6.0
  build_runner: ^1.9.0
#
