name: boond_dart
description: Boond Manager API.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  #  path: ^1.6.0
  # utilities
  logging: ^1.0.0
  http: ^1.2.0
  http_auth : ^1.0.0
  json_annotation: ^4.0.0
  jaguar_jwt: ^3.0.0
  intl: 0.19.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  # in terminal launch 'dart run build_runner watch --delete-conflicting-outputs' for dynamic cede generation
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
#
#


